# Generated by Django 2.1.7 on 2019-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reactorone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactorone',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
