# Generated by Django 2.1.7 on 2019-03-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190331_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='passw',
        ),
    ]
